function n(v, d = 5) { if (v === undefined || v === null || v === '') return null; const x = Number(v); return Number.isFinite(x) ? Number(x.toFixed(d)) : null; }
function nums(a) { return (a || []).map(Number).filter(Number.isFinite); }
function ema(values, period) { const clean = nums(values); if (clean.length < period) return null; const m = 2 / (period + 1); let e = clean.slice(0, period).reduce((s, v) => s + v, 0) / period; for (const v of clean.slice(period)) e = (v - e) * m + e; return n(e); }
function rsi(values, period = 14) { const c = nums(values); if (c.length <= period) return null; let gains = 0, losses = 0; for (let i = 1; i <= period; i++) { const d = c[i] - c[i - 1]; if (d >= 0) gains += d; else losses -= d; } let ag = gains / period, al = losses / period; for (let i = period + 1; i < c.length; i++) { const d = c[i] - c[i - 1]; ag = (ag * (period - 1) + Math.max(d, 0)) / period; al = (al * (period - 1) + Math.max(-d, 0)) / period; } return al === 0 ? 100 : n(100 - (100 / (1 + ag / al)), 2); }
function atr(candles, period = 14) { if (!Array.isArray(candles) || candles.length <= period) return null; const trs = []; for (let i = 1; i < candles.length; i++) { const h = Number(candles[i].high), l = Number(candles[i].low), pc = Number(candles[i - 1].close); if ([h,l,pc].every(Number.isFinite)) trs.push(Math.max(h - l, Math.abs(h - pc), Math.abs(l - pc))); } if (trs.length < period) return null; return n(trs.slice(-period).reduce((s, v) => s + v, 0) / period); }
function bollinger(values, period = 20, mult = 2) { const c = nums(values); if (c.length < period) return null; const s = c.slice(-period); const mid = s.reduce((a,b)=>a+b,0)/period; const dev = Math.sqrt(s.reduce((a,b)=>a+((b-mid)**2),0)/period); return { upper: n(mid + mult * dev), middle: n(mid), lower: n(mid - mult * dev) }; }
function levels(candles, lastClose) { const r = (candles || []).slice(-80); if (!r.length || !Number.isFinite(lastClose)) return { support: null, resistance: null }; const highs = nums(r.map(c=>c.high)), lows = nums(r.map(c=>c.low)); return { support: n((lows.filter(v=>v<=lastClose).sort((a,b)=>b-a)[0] ?? Math.min(...lows))), resistance: n((highs.filter(v=>v>=lastClose).sort((a,b)=>a-b)[0] ?? Math.max(...highs))) }; }
function previousHighLow(candles) { const c = candles || []; const prev = (tf) => { const groups = new Map(); c.forEach(x => { const d = new Date(x.time); if (!Number.isFinite(d.getTime())) return; const k = tf === 'week' ? `${d.getUTCFullYear()}-W${Math.floor((Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()) - Date.UTC(d.getUTCFullYear(),0,1))/604800000)}` : d.toISOString().slice(0,10); if (!groups.has(k)) groups.set(k, []); groups.get(k).push(x); }); const vals = [...groups.values()]; const p = vals.length > 1 ? vals[vals.length - 2] : []; return p.length ? { high: n(Math.max(...nums(p.map(x=>x.high)))), low: n(Math.min(...nums(p.map(x=>x.low)))) } : null; }; return { previousDay: prev('day'), previousWeek: prev('week') }; }
function volumeSummary(candles) { const vols = nums((candles || []).map(c=>c.volume)); return { available: vols.length > 0, candlesWithVolume: vols.length, latest: vols.length ? n(vols[vols.length - 1], 2) : null, averageRecent: vols.length ? n(vols.slice(-20).reduce((s,v)=>s+v,0)/Math.min(20, vols.length), 2) : null }; }
function summarizeTimeframe(timeframe, candles = []) { const closes = nums(candles.map(c=>c.close)); const lastClose = closes.at(-1) ?? null; const e50 = ema(closes,50), e100 = ema(closes,100), e200 = ema(closes,200); const align = [e50,e100,e200].every(Number.isFinite) ? (e50 > e100 && e100 > e200 ? 'bullish alignment' : e50 < e100 && e100 < e200 ? 'bearish alignment' : 'mixed') : 'unavailable'; const trend = align.includes('bullish') ? 'bullish' : align.includes('bearish') ? 'bearish' : 'neutral'; const lv = levels(candles, lastClose); return { timeframe, candleCount: candles.length, lastClose: n(lastClose), trend, ema50: e50, ema100: e100, ema200: e200, emaAlignment: align, rsi: rsi(closes,14), atr: atr(candles,14), bollinger: bollinger(closes,20,2), support: lv.support, resistance: lv.resistance, previousHighLow: previousHighLow(candles), volumeSummary: volumeSummary(candles), dataQuality: candles.length >= 200 ? 'complete' : candles.length >= 50 ? 'limited' : candles.length ? 'insufficient' : 'missing' }; }
module.exports = { ema, rsi, atr, bollinger, levels, previousHighLow, volumeSummary, summarizeTimeframe };
